-- MySQL Script generated by MySQL Workbench
-- Fri May 15 17:45:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Space_Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Space_Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Space_Company` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Engineers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Engineers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Engineers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `speciality` ENUM('Aerospace', 'Mechanical', 'Computer Hardware', 'Electronics') NOT NULL,
  `space_company_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Engineers_Space_Company1_idx` (`space_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Engineers_Space_Company1`
    FOREIGN KEY (`space_company_id`)
    REFERENCES `mydb`.`Space_Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `space_company_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Stations_Space_Company1_idx` (`space_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stations_Space_Company1`
    FOREIGN KEY (`space_company_id`)
    REFERENCES `mydb`.`Space_Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Astronauts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Astronauts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Astronauts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `duty` ENUM('Captain', 'Pilot', 'General Specialist', 'Cargo Specialist', 'Flight Engineer') NOT NULL,
  `stations_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Astronauts_Stations1_idx` (`stations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Astronauts_Stations1`
    FOREIGN KEY (`stations_id`)
    REFERENCES `mydb`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `stations_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Addresses_Stations1_idx` (`stations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Stations1`
    FOREIGN KEY (`stations_id`)
    REFERENCES `mydb`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rockets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rockets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rockets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `weight` FLOAT NULL,
  `fuel_capacity` FLOAT NULL,
  `passengers_capacity` INT NULL,
  `cargo_capacity` INT NULL,
  `space_company_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Rockets_Space_Company1_idx` (`space_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rockets_Space_Company1`
    FOREIGN KEY (`space_company_id`)
    REFERENCES `mydb`.`Space_Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Missions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Missions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Missions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `objective` VARCHAR(45) NOT NULL,
  `span_in_years` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CEO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CEO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CEO` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `space_company_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_CEO_Space_Company1_idx` (`space_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_CEO_Space_Company1`
    FOREIGN KEY (`space_company_id`)
    REFERENCES `mydb`.`Space_Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rocket_Mission_Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rocket_Mission_Date` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rocket_Mission_Date` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `launch_date` DATE NOT NULL,
  `rockets_id` INT UNSIGNED NOT NULL,
  `missions_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Rocket_Mission_Date_Rockets1_idx` (`rockets_id` ASC) VISIBLE,
  INDEX `fk_Rocket_Mission_Date_Missions1_idx` (`missions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rocket_Mission_Date_Rockets1`
    FOREIGN KEY (`rockets_id`)
    REFERENCES `mydb`.`Rockets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rocket_Mission_Date_Missions1`
    FOREIGN KEY (`missions_id`)
    REFERENCES `mydb`.`Missions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Satellites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Satellites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Satellites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `weight` FLOAT NULL,
  `cargo_capacity` FLOAT NULL,
  `fuel_capacity` FLOAT NULL,
  `stations_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Satellites_Stations1_idx` (`stations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Satellites_Stations1`
    FOREIGN KEY (`stations_id`)
    REFERENCES `mydb`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Satellite_Mission_Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Satellite_Mission_Date` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Satellite_Mission_Date` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `launch_date` DATETIME NOT NULL,
  `satellites_id` INT UNSIGNED NOT NULL,
  `missions_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Satellite_Mission_Date_Satellites1_idx` (`satellites_id` ASC) VISIBLE,
  INDEX `fk_Satellite_Mission_Date_Missions1_idx` (`missions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Satellite_Mission_Date_Satellites1`
    FOREIGN KEY (`satellites_id`)
    REFERENCES `mydb`.`Satellites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Satellite_Mission_Date_Missions1`
    FOREIGN KEY (`missions_id`)
    REFERENCES `mydb`.`Missions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
